# Generated by Django 4.2.6 on 2024-04-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_skin_user_skins'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
